# Generated by Django 4.1.5 on 2023-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(default='Dublin', max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='country',
            field=models.CharField(default='Ireland', max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='number',
            field=models.CharField(default='7 & 8', max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.CharField(default='Belvedere Place, Mountjoy Square', max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='color',
            field=models.CharField(default='Brick Red', max_length=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(default='Dorset College', max_length=50),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
