# Generated by Django 4.1.5 on 2023-02-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_city_building_country_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='residential',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='street',
            field=models.CharField(default='Belvedere Place, Mountjoy Square', max_length=100),
        ),
    ]
